// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: fsp.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace FlightSimulator {
  public static partial class FlightSimulatorService
  {
    static readonly string __ServiceName = "FlightSimulator.FlightSimulatorService";

    static readonly grpc::Marshaller<global::FlightSimulator.DummyQ> __Marshaller_FlightSimulator_DummyQ = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::FlightSimulator.DummyQ.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::FlightSimulator.CameraStreamQ> __Marshaller_FlightSimulator_CameraStreamQ = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::FlightSimulator.CameraStreamQ.Parser.ParseFrom);

    static readonly grpc::Method<global::FlightSimulator.DummyQ, global::FlightSimulator.CameraStreamQ> __Method_GetCameraStream = new grpc::Method<global::FlightSimulator.DummyQ, global::FlightSimulator.CameraStreamQ>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetCameraStream",
        __Marshaller_FlightSimulator_DummyQ,
        __Marshaller_FlightSimulator_CameraStreamQ);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::FlightSimulator.FspReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of FlightSimulatorService</summary>
    public abstract partial class FlightSimulatorServiceBase
    {
      public virtual global::System.Threading.Tasks.Task GetCameraStream(global::FlightSimulator.DummyQ request, grpc::IServerStreamWriter<global::FlightSimulator.CameraStreamQ> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for FlightSimulatorService</summary>
    public partial class FlightSimulatorServiceClient : grpc::ClientBase<FlightSimulatorServiceClient>
    {
      /// <summary>Creates a new client for FlightSimulatorService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public FlightSimulatorServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for FlightSimulatorService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public FlightSimulatorServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected FlightSimulatorServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected FlightSimulatorServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::FlightSimulator.CameraStreamQ> GetCameraStream(global::FlightSimulator.DummyQ request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCameraStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::FlightSimulator.CameraStreamQ> GetCameraStream(global::FlightSimulator.DummyQ request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetCameraStream, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override FlightSimulatorServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new FlightSimulatorServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(FlightSimulatorServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetCameraStream, serviceImpl.GetCameraStream).Build();
    }

  }
}
#endregion
